server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置定时任务的线程池数量（如果仅仅想要增加定时任务线程池的线程数，可以直接在配置文件中更改
#task:
#  scheduling:
#    pool:
#      size: 5

  thymeleaf:
    prefix: classpath:/templates/ # 访问template下的html文件需要配置模板，映射
    mode: HTML
    suffix: .html
    cache: false # 开发时关闭缓存,不然没法看到实时页面

  rabbitmq:
    username: doone
    password: xdw#2020
    addresses: 36.148.23.208
    port: 15672
    virtual-host: /
    #  如果你们在配置确认回调，测试发现无法触发回调函数，那么存在原因也许是因为版本导致的配置项不起效，
    #  消息回调的配置   可以把publisher-confirms: true 替换为 publisher-confirm-type: correlated
    publisher-confirms: true
    cache:
      connection:
        mode: channel
    #       多个连接,多个channel
    #       mode: connection



    # 打印SQL
    logging:
      level:
        com.example.mapper: debug

    mybatis:
      # XML扫描路径
      mapper-locations: classpath:mapper/**/*.xml
      # 通用Mapper的方法会自动转换驼峰，但手写的SQL需要开启才能转换
      configuration:
        map-underscore-to-camel-case: on